services:
  broker:
    image: quay.io/darrenjoelclark/cp-for-dev-kafka:7.1.1
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    volumes:
      - brokerdata:/data
    environment:
      KAFKA_LOG_DIRS: /data
      KAFKA_LISTENERS: CONTROLLER://:9093,PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  schema-registry:
    image: quay.io/darrenjoelclark/cp-for-dev-schema-registry:7.1.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8081'
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://broker:29092'
    healthcheck:
      test: curl -f http://localhost:8081
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s


volumes:
  brokerdata: {}
