#!/usr/bin/env bash

set -euo pipefail

# Pulled from the provided /etc/kafka/kraft/server.properties
#
# cat $CONFLUENT_HOME/etc/kafka/kraft/server.properties | \
#   grep -v '^#' | \
#   grep -E '^.' | \
#   awk 'BEGIN { FS="=" } { gsub(/\./, "_", $1); print "export KAFKA_" toupper($1) "=\"${KAFKA_" toupper($1) ":-" $2 "}\"" }'

export KAFKA_PROCESS_ROLES="${KAFKA_PROCESS_ROLES:-broker,controller}"
export KAFKA_NODE_ID="${KAFKA_NODE_ID:-1}"
export KAFKA_CONTROLLER_QUORUM_VOTERS="${KAFKA_CONTROLLER_QUORUM_VOTERS:-1@localhost:9093}"
export KAFKA_LISTENERS="${KAFKA_LISTENERS:-PLAINTEXT://:9092,CONTROLLER://:9093}"
export KAFKA_INTER_BROKER_LISTENER_NAME="${KAFKA_INTER_BROKER_LISTENER_NAME:-PLAINTEXT}"
export KAFKA_ADVERTISED_LISTENERS="${KAFKA_ADVERTISED_LISTENERS:-PLAINTEXT://localhost:9092}"
export KAFKA_CONTROLLER_LISTENER_NAMES="${KAFKA_CONTROLLER_LISTENER_NAMES:-CONTROLLER}"
export KAFKA_LISTENER_SECURITY_PROTOCOL_MAP="${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:-CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL}"
export KAFKA_NUM_NETWORK_THREADS="${KAFKA_NUM_NETWORK_THREADS:-3}"
export KAFKA_NUM_IO_THREADS="${KAFKA_NUM_IO_THREADS:-8}"
export KAFKA_SOCKET_SEND_BUFFER_BYTES="${KAFKA_SOCKET_SEND_BUFFER_BYTES:-102400}"
export KAFKA_SOCKET_RECEIVE_BUFFER_BYTES="${KAFKA_SOCKET_RECEIVE_BUFFER_BYTES:-102400}"
export KAFKA_SOCKET_REQUEST_MAX_BYTES="${KAFKA_SOCKET_REQUEST_MAX_BYTES:-104857600}"
export KAFKA_LOG_DIRS="${KAFKA_LOG_DIRS:-/tmp/kraft-combined-logs}"
export KAFKA_NUM_PARTITIONS="${KAFKA_NUM_PARTITIONS:-1}"
export KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR="${KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR:-1}"
export KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR="${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-1}"
export KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR="${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR:-1}"
export KAFKA_TRANSACTION_STATE_LOG_MIN_ISR="${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR:-1}"
export KAFKA_LOG_RETENTION_HOURS="${KAFKA_LOG_RETENTION_HOURS:-168}"
export KAFKA_LOG_SEGMENT_BYTES="${KAFKA_LOG_SEGMENT_BYTES:-1073741824}"
export KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS="${KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS:-300000}"
export KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS="${KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS:-0}"

# Convert all KAFKA_* env vars into a .properties file
gomplate -f server.properties.tmpl -o server.properties

if [[ ! -f "$KAFKA_LOG_DIRS"/meta.properties ]]; then
  cluster_id="$(kafka-storage random-uuid)"
  kafka-storage format --config server.properties --cluster-id "$cluster_id"
fi

kafka-server-start server.properties
